title: NES Development

url: "http://timcheeseman.com"
baseurl: "/nesdev"

description: NES Development Tutorial

encoding: utf-8
markdown: kramdown
sass:
    style: :compressed
timezone: America/New_York

