title: Learn to Make NES Games

url: "https://timcheeseman.com"
baseurl: "/nesdev"
github_url: "https://github.com/cirla/nesdev"

description: NES Development Tutorial

encoding: utf-8
sass:
    style: :compressed
timezone: America/New_York

